services:
  db:
    container_name: postgres
    image: postgres:16.3
    environment:
      POSTGRES_USER: kareemabdo
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - postgres
    restart: unless-stopped

  spring-boot-example:
    container_name: kareemabdo-api
    image: kareemabdose/spring-boot-example
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/customer
    ports:
      - "8080:8080"
    networks:
      - postgres
    depends_on:
      - db
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
